main: net.warvale.core.Main
name: GameCore
version: 1.1.4
author: Warvale
description: A CTF plugin.
depend: [StaffCore]
commands:
  gamever:
    description: Test if the core of the plugin is functioning.
  join:
    description: Join the game.
  leave:
    description: Leave the game.
  start:
    description: Automatically start the game.
  classes:
    description: List all classes.
  map:
    description: manage maps
  teststart:
    description: tests the bossbar countdown
