main: net.warvale.core.Main
name: GameCore
version: 1.1.4
author: Warvale
description: A CTF plugin.
depend: [StaffCore]
commands:
  gamever:
    description: Test if the core of the plugin is functioning.
  join:
    description: Join the game.
  leave:
    description: Leave the game.
  start:
    description: Automatically start the game.
  classes:
    description: List all classes.
  map:
    description: manage maps
  teststart:
    description: Tests the bossbar countdown.
  msg:
    description: Send another player a private message.
  r:
    description: Send a message to the player you most recently sent a message to.
  vote:
    description: Use this to vote for which map is played.
  setstate:
    description: Sets the state of the game